# Databricks notebook source
# MAGIC %md
# MAGIC # ESMA XML Loader — Bronze SDP
# MAGIC Parameterised for EMIR + MiFIR.
# MAGIC
# MAGIC **3-table topology:**
# MAGIC - `{prefix}_raw` — Auto Loader → Delta, ALL rows (good + bad).
# MAGIC - `{prefix}_quarantine` — bad rows from `{prefix}_raw` + xsd error annotation.
# MAGIC - `{prefix}_file_headers` — one row per file, lxml-extracted header struct.
# MAGIC
# MAGIC Config via `spark.conf` (see `resources/bundle.{emir,mifir}_resources.yml`).

# COMMAND ----------

from __future__ import annotations

import json

from pyspark import pipelines as dp
from pyspark.sql import functions as F
from pyspark.sql.types import StringType, StructType

# COMMAND ----------

# MAGIC %md
# MAGIC ## Pipeline configuration
# MAGIC Resolved at import time from `resources/bundle.*_resources.yml`.

# COMMAND ----------

CATALOG = spark.conf.get("catalog")
RAW_SCHEMA = spark.conf.get("raw_schema")
TABLE_PREFIX = spark.conf.get("table_prefix")
LANDING_PATH = spark.conf.get("landing_path")
ROW_TAG = spark.conf.get("row_tag")
XML_SCHEMA_PYLD_PATH = spark.conf.get("xml_schema_pyld_path")
XML_SCHEMA_HDR_PYLD_METADATA_PATH = spark.conf.get("xml_schema_hdr_pyld_metadata_path")
XML_XSD_SCHEMA_PYLD_PATH = spark.conf.get("xml_xsd_schema_pyld_path")

# Row-level XSD enforcement (cloudFiles.rowValidationXSDPath + xsd_error UDF).
ENABLE_XSD_VALIDATION = spark.conf.get("enable_xsd_validation", "true").lower() == "true"

# ESMA filename-regex extraction (FileBatchIndex/FileBatchSize/FileVersion/ESMADate).
# Set False for non-ESMA filenames; the four columns emit NULL passthrough.
ENABLE_FILENAME_REGEX = spark.conf.get("enable_filename_regex", "true").lower() == "true"

# cloudFiles.cleanSource: OFF | MOVE | DELETE. Retention is the *wait after
# processing* before a file becomes cleanup-eligible — must exceed the
# downstream lxml re-read window (default "7 days" >> typical lag).
# moveDestination must live in the same UC volume / external location as source.
CLEAN_SOURCE_MODE = spark.conf.get("clean_source_mode", "OFF").upper()
CLEAN_SOURCE_MOVE_DEST = spark.conf.get("clean_source_move_destination", "")
CLEAN_SOURCE_RETENTION = spark.conf.get("clean_source_retention", "7 days")

TBL_RAW = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_raw"
TBL_QUARANTINE = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_quarantine"
TBL_FILE_HEADERS = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_file_headers"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Filename regex extraction
# MAGIC Customer-replaceable. Default parses the ESMA convention
# MAGIC `<6-digit batch index>-<1-digit batch size>_<6-digit YYMMDD>_*.xml`.
# MAGIC Keep the four output column names (FileBatchIndex/FileBatchSize/FileVersion/ESMADate);
# MAGIC redefine the extraction logic for other regimes.

# COMMAND ----------

_FILE_INDEX_PATTERN = r"\d\d\d\d\d\d-\d"
_ESMA_DATE_PATTERN = r"-\d\d\d\d\d\d_"


def _add_filename_regex_columns(df):
    """Append FileBatchIndex / FileBatchSize / FileVersion / ESMADate from `file_name`."""
    if not ENABLE_FILENAME_REGEX:
        return (
            df
            .withColumn("FileBatchIndex", F.lit(None).cast("string"))
            .withColumn("FileBatchSize", F.lit(None).cast("string"))
            .withColumn("FileVersion", F.lit(None).cast("string"))
            .withColumn("ESMADate", F.lit(None).cast("string"))
        )
    return (
        df
        .withColumn(
            "FileBatchIndex",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                1, 3,
            ),
        )
        .withColumn(
            "FileBatchSize",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                4, 3,
            ),
        )
        .withColumn(
            "FileVersion",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                8, 1,
            ),
        )
        .withColumn(
            "ESMADate",
            F.concat(
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    2, 2,
                ),
                F.lit("-"),
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    4, 2,
                ),
                F.lit("-"),
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    6, 2,
                ),
            ),
        )
    )

# COMMAND ----------

# MAGIC %md
# MAGIC ## Schema loading
# MAGIC JSON schemas + row-tag XSD pre-generated by `src/notebooks/0_1_xml_schema_xsd.py`.

# COMMAND ----------

def _read_schema(file_path: str) -> StructType:
    """Load a Spark JSON schema file into a StructType."""
    with open(file_path, "r") as f:
        return StructType.fromJson(json.loads(f.read()))


XML_PYLD_SCHEMA: StructType = _read_schema(XML_SCHEMA_PYLD_PATH)
XML_HDR_PYLD_METADATA_SCHEMA: StructType = _read_schema(XML_SCHEMA_HDR_PYLD_METADATA_PATH)

# COMMAND ----------

# MAGIC %md
# MAGIC ## XSD-validation UDF
# MAGIC Used by `quarantine` only — annotates already-failed rows with a
# MAGIC human-readable lxml error. Schema cached per worker per XSD path.

# COMMAND ----------

_xsd_cache: dict = {}


def _get_xsd_schema(xsd_path: str):
    """Compile and cache an lxml XMLSchema per path, once per worker."""
    if xsd_path not in _xsd_cache:
        from lxml import etree
        with open(xsd_path, "rb") as f:
            _xsd_cache[xsd_path] = etree.XMLSchema(etree.XML(f.read()))
    return _xsd_cache[xsd_path]


@F.udf(returnType=StringType())
def xsd_error(xml_str: str, xsd_path: str) -> str:
    """Return a verbose XSD-validation error message, or 'XML is valid'."""
    from lxml import etree
    try:
        if xml_str is None:
            return "Invalid XML: input is null"
        schema = _get_xsd_schema(xsd_path)
        schema.assertValid(etree.fromstring(xml_str.encode("utf-8")))
        return "XML is valid"
    except Exception as e:
        return f"Invalid XML: {str(e)}"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Header-extraction UDF
# MAGIC `iterparse`, stop at first row-tag, strip empty elements, return
# MAGIC header-only XML as a string. Lenient on failure (returns `None`).

# COMMAND ----------

def _strip_namespace(tag: str) -> str:
    """Strip ``{ns}name`` prefix from an lxml tag."""
    return tag.split("}")[-1] if "}" in tag else tag


def _remove_empty_elements(element) -> bool:
    """Recursively drop elements that have no children, attributes, or text."""
    children_to_remove = []
    for child in list(element):
        if _remove_empty_elements(child):
            children_to_remove.append(child)
    for child in children_to_remove:
        element.remove(child)
    has_children = len(list(element)) > 0
    has_attributes = bool(element.attrib)
    has_meaningful_text = (
        (element.text and element.text.strip())
        or (element.tail and element.tail.strip())
    )
    return not has_children and not has_attributes and not has_meaningful_text


def _extract_hdr_pyld_metadata(file_path: str, row_tag: str) -> str | None:
    """Return the header-only XML for a single file, stopping at row_tag."""
    from lxml import etree
    try:
        context = etree.iterparse(file_path, events=("start", "end"), recover=True)
        element_stack = []
        skip_depth = 0
        root = None
        found_row_tag = False

        for event, elem in context:
            tag_name = _strip_namespace(elem.tag)
            if event == "start":
                if tag_name == row_tag and not found_row_tag:
                    found_row_tag = True
                    elem.clear()
                    break
                should_skip = (skip_depth > 0) or (tag_name == row_tag)
                if should_skip:
                    skip_depth += 1
                else:
                    new_elem = etree.Element(elem.tag, attrib=elem.attrib)
                    new_elem.tag = _strip_namespace(new_elem.tag)
                    if element_stack:
                        element_stack[-1].append(new_elem)
                    else:
                        root = new_elem
                    element_stack.append(new_elem)
            elif event == "end":
                if skip_depth > 0:
                    skip_depth -= 1
                elif element_stack:
                    current_elem = element_stack.pop()
                    current_elem.text = elem.text
                    current_elem.tail = elem.tail
                elem.clear()

        if root is not None:
            _remove_empty_elements(root)
            return etree.tostring(root, encoding="unicode", pretty_print=True)
        return None
    except Exception as e:
        # Lenient: failure surfaces as null hdr_pyld_metadata downstream.
        print(f"Error processing {file_path}: {e}")
        return None


extract_hdr_pyld_metadata_udf = F.udf(_extract_hdr_pyld_metadata, StringType())

# COMMAND ----------

# MAGIC %md
# MAGIC ## Table 1 of 3 — `{prefix}_raw` (public)
# MAGIC Auto Loader cloudFiles → Delta. **ALL rows (good + bad)** in a single
# MAGIC table — `corrupted_record` populated only for malformed XML rows.
# MAGIC Silver should filter `corrupted_record IS NULL` if it wants only good
# MAGIC rows; `{prefix}_quarantine` is a downstream filter for bad rows.

# COMMAND ----------

@dp.table(
    name=TBL_RAW,
    comment=(
        "Public: ALL rows from Auto Loader (good + bad). `corrupted_record` "
        "is populated only on malformed rows. Single source for downstream "
        "{prefix}_quarantine and {prefix}_file_headers tables, and for silver. "
        "Silver tables that want only good rows should filter "
        "`corrupted_record IS NULL`."
    ),
    cluster_by_auto=True,
)
def raw():
    loader = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "xml")
        .option("rowTag", ROW_TAG)
        .option("columnNameOfCorruptRecord", "corrupted_record")
        .option("rescuedDataColumn", "rescued_data")
        .option("mode", "PERMISSIVE")
    )
    if ENABLE_XSD_VALIDATION:
        loader = loader.option("rowValidationXSDPath", XML_XSD_SCHEMA_PYLD_PATH)

    # cloudFiles.cleanSource — see CLEAN_SOURCE_* config block above.
    if CLEAN_SOURCE_MODE in ("MOVE", "DELETE"):
        loader = (
            loader
            .option("cloudFiles.cleanSource", CLEAN_SOURCE_MODE)
            .option(
                "cloudFiles.cleanSource.retentionDuration",
                CLEAN_SOURCE_RETENTION,
            )
        )
        if CLEAN_SOURCE_MODE == "MOVE":
            loader = loader.option(
                "cloudFiles.cleanSource.moveDestination",
                CLEAN_SOURCE_MOVE_DEST,
            )

    df = (
        loader
        .schema(XML_PYLD_SCHEMA)
        .load(LANDING_PATH)
        .withColumn("file_path", F.col("_metadata.file_path"))
        .withColumn("file_name", F.col("_metadata.file_name"))
        .withColumn(
            "_file_modification_time",
            F.col("_metadata.file_modification_time"),
        )
        .withColumn("_ingested_at", F.current_timestamp())
    )
    # Defensive: some Spark/DBR builds don't materialize corrupted_record
    # unless it's in the schema. NULL passthrough keeps the split working.
    if "corrupted_record" not in df.columns:
        df = df.withColumn("corrupted_record", F.lit(None).cast("string"))
    return df

# COMMAND ----------

# MAGIC %md
# MAGIC ## Table 2 of 3 — `{prefix}_quarantine` (public)
# MAGIC Bad rows filtered from `{prefix}_raw` + human-readable
# MAGIC `xsd_validation_result`. When XSD validation is disabled, only
# MAGIC JSON-schema parse failures land here.

# COMMAND ----------

@dp.table(
    name=TBL_QUARANTINE,
    comment=(
        "Public: malformed XML rows filtered from {prefix}_raw "
        "(corrupted_record IS NOT NULL), enriched with xsd_validation_result "
        "(human-readable lxml error)."
    ),
    cluster_by_auto=True,
)
def quarantine():
    bad_rows = (
        spark.readStream.table(TBL_RAW)
        .filter(F.col("corrupted_record").isNotNull())
    )
    if ENABLE_XSD_VALIDATION:
        bad_rows = bad_rows.withColumn(
            "xsd_validation_result",
            xsd_error(F.col("corrupted_record"), F.lit(XML_XSD_SCHEMA_PYLD_PATH)),
        )
    else:
        bad_rows = bad_rows.withColumn(
            "xsd_validation_result",
            F.lit("XSD validation disabled"),
        )
    return bad_rows.select(
        "file_path",
        "file_name",
        "_file_modification_time",
        "_ingested_at",
        "corrupted_record",
        "rescued_data",
        "xsd_validation_result",
    )

# COMMAND ----------

# MAGIC %md
# MAGIC ## Table 3 of 3 — `{prefix}_file_headers` (public)
# MAGIC One row per unique source file with `hdr_pyld_metadata` (lxml-extracted
# MAGIC BAH + Document header) and filename-regex columns. Silver `submission_file`
# MAGIC reads from this table directly.

# COMMAND ----------

@dp.table(
    name=TBL_FILE_HEADERS,
    comment=(
        "Public: one row per ingested XML file. hdr_pyld_metadata struct "
        "(BAH + Document header, lxml-extracted) plus filename regex columns "
        "(FileBatchIndex/FileBatchSize/FileVersion/ESMADate). Silver "
        "submission_file reads from this table."
    ),
    cluster_by_auto=True,
)
def file_headers():
    return (
        spark.readStream.table(TBL_RAW)
        .filter(F.col("corrupted_record").isNull())
        .select("file_path", "file_name", "_file_modification_time", "_ingested_at")
        .dropDuplicates(["file_path"])
        .select(
            "file_path",
            "file_name",
            "_file_modification_time",
            "_ingested_at",
            extract_hdr_pyld_metadata_udf(
                F.col("file_path"), F.lit(ROW_TAG)
            ).alias("_hdr_xml"),
        )
        .withColumn(
            "hdr_pyld_metadata",
            F.from_xml(F.col("_hdr_xml"), XML_HDR_PYLD_METADATA_SCHEMA),
        )
        .drop("_hdr_xml")
        .transform(_add_filename_regex_columns)
    )
