"""ESMA XML Loader — Spark Declarative Pipeline.

Parameterized SDP source backing both the EMIR and MiFIR XML loader pipelines.
Reads XML files via Auto Loader, splits malformed rows into a quarantine table
enriched with an lxml XSD-validation error, and produces a public
``{prefix}_raw`` streaming table with payload + header metadata joined per file.

All inputs are supplied via ``spark.conf`` — see the bundle pipeline
``configuration`` block in ``resources/bundle.{emir,mifir}_resources.yml``.

Reference: docs/superpowers/specs/2026-05-11-sdp-xml-loader-design.md
"""

from __future__ import annotations

import json

from pyspark import pipelines as dp
from pyspark.sql import functions as F
from pyspark.sql.types import StringType, StructType

# --------------------------------------------------------------------------
# Pipeline configuration (set in resources/bundle.*_resources.yml under
# resources.pipelines.<name>.configuration). All values are resolved at
# import time so the @dp.table decorators can reference them.
# --------------------------------------------------------------------------

CATALOG = spark.conf.get("catalog")
RAW_SCHEMA = spark.conf.get("raw_schema")
TABLE_PREFIX = spark.conf.get("table_prefix")
LANDING_PATH = spark.conf.get("landing_path")
ROW_TAG = spark.conf.get("row_tag")
XML_SCHEMA_PYLD_PATH = spark.conf.get("xml_schema_pyld_path")
XML_SCHEMA_HDR_PYLD_METADATA_PATH = spark.conf.get("xml_schema_hdr_pyld_metadata_path")
XML_XSD_SCHEMA_PYLD_PATH = spark.conf.get("xml_xsd_schema_pyld_path")
WATERMARK_INTERVAL = spark.conf.get("watermark_interval", "15 minutes")

# Fully qualified table names — published to {catalog}.{raw_schema}.
TBL_RAW_XML_PAYLOAD = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_raw_xml_payload"
TBL_QUARANTINE = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_quarantine"
TBL_RAW = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_raw"

# Filename-regex patterns used inside the inline self-join in `raw` to
# extract FileBatchIndex / FileBatchSize / FileVersion / ESMADate from
# the source XML filename. Module-level so they're compiled once.
_FILE_INDEX_PATTERN = r"\d\d\d\d\d\d-\d"
_ESMA_DATE_PATTERN = r"-\d\d\d\d\d\d_"


def _read_schema(file_path: str) -> StructType:
    """Load a Spark JSON schema file into a StructType.

    Ported from src/notebooks/1_xml_file_loader_body.py — schemas are
    pre-generated by the XSD-conversion notebook and live as JSON files
    in a UC Volume next to the source XSDs.
    """
    with open(file_path, "r") as f:
        return StructType.fromJson(json.loads(f.read()))


# Loaded once at pipeline-start.
XML_PYLD_SCHEMA: StructType = _read_schema(XML_SCHEMA_PYLD_PATH)
XML_HDR_PYLD_METADATA_SCHEMA: StructType = _read_schema(XML_SCHEMA_HDR_PYLD_METADATA_PATH)


# --------------------------------------------------------------------------
# XSD-validation UDF (used by the quarantine table only).
#
# The XSD schema object is compiled once per Python worker per XSD path
# via _xsd_cache — Auto Loader's per-row XSD validation already runs
# upstream; this UDF only fires on the small minority of rows that
# already failed validation, where we want a human-readable error to
# surface in the quarantine table.
# --------------------------------------------------------------------------

_xsd_cache: dict = {}


def _get_xsd_schema(xsd_path: str):
    """Compile and cache an lxml XMLSchema per path, once per worker."""
    if xsd_path not in _xsd_cache:
        from lxml import etree
        with open(xsd_path, "rb") as f:
            _xsd_cache[xsd_path] = etree.XMLSchema(etree.XML(f.read()))
    return _xsd_cache[xsd_path]


@F.udf(returnType=StringType())
def xsd_error(xml_str: str, xsd_path: str) -> str:
    """Return a verbose XSD-validation error message, or 'XML is valid'."""
    from lxml import etree
    try:
        if xml_str is None:
            return "Invalid XML: input is null"
        schema = _get_xsd_schema(xsd_path)
        schema.assertValid(etree.fromstring(xml_str.encode("utf-8")))
        return "XML is valid"
    except Exception as e:
        return f"Invalid XML: {str(e)}"


# --------------------------------------------------------------------------
# Header-extraction UDF.
#
# Reads the XML file via lxml.iterparse, stops at the first row-tag
# element, strips empty elements, and returns the header-only XML as a
# string. Lenient on failure (returns None) — preserving today's
# notebook behavior. A dp.expect on the parsed header struct is a
# deliberate follow-up, not part of this branch.
# --------------------------------------------------------------------------


def _strip_namespace(tag: str) -> str:
    """Strip ``{ns}name`` prefix from an lxml tag."""
    return tag.split("}")[-1] if "}" in tag else tag


def _remove_empty_elements(element) -> bool:
    """Recursively drop elements that have no children, attributes, or text."""
    children_to_remove = []
    for child in list(element):
        if _remove_empty_elements(child):
            children_to_remove.append(child)
    for child in children_to_remove:
        element.remove(child)
    has_children = len(list(element)) > 0
    has_attributes = bool(element.attrib)
    has_meaningful_text = (
        (element.text and element.text.strip())
        or (element.tail and element.tail.strip())
    )
    return not has_children and not has_attributes and not has_meaningful_text


def _extract_hdr_pyld_metadata(file_path: str, row_tag: str) -> str | None:
    """Return the header-only XML for a single file, stopping at row_tag."""
    from lxml import etree
    try:
        context = etree.iterparse(file_path, events=("start", "end"), recover=True)
        element_stack = []
        skip_depth = 0
        root = None
        found_row_tag = False

        for event, elem in context:
            tag_name = _strip_namespace(elem.tag)
            if event == "start":
                if tag_name == row_tag and not found_row_tag:
                    found_row_tag = True
                    elem.clear()
                    break
                should_skip = (skip_depth > 0) or (tag_name == row_tag)
                if should_skip:
                    skip_depth += 1
                else:
                    new_elem = etree.Element(elem.tag, attrib=elem.attrib)
                    new_elem.tag = _strip_namespace(new_elem.tag)
                    if element_stack:
                        element_stack[-1].append(new_elem)
                    else:
                        root = new_elem
                    element_stack.append(new_elem)
            elif event == "end":
                if skip_depth > 0:
                    skip_depth -= 1
                elif element_stack:
                    current_elem = element_stack.pop()
                    current_elem.text = elem.text
                    current_elem.tail = elem.tail
                elem.clear()

        if root is not None:
            _remove_empty_elements(root)
            return etree.tostring(root, encoding="unicode", pretty_print=True)
        return None
    except Exception as e:
        # Lenient: failure surfaces as null hdr_pyld_metadata downstream.
        print(f"Error processing {file_path}: {e}")
        return None


extract_hdr_pyld_metadata_udf = F.udf(_extract_hdr_pyld_metadata, StringType())


# --------------------------------------------------------------------------
# Table 1 of 3: {prefix}_raw_xml_payload (intermediate — internal use)
#
# Auto Loader reads XML files from the landing path. ALL rows (good +
# corrupted) land here. Downstream tables filter on corrupted_record.
# --------------------------------------------------------------------------


@dp.table(
    name=TBL_RAW_XML_PAYLOAD,
    comment=(
        "Internal: raw XML payload rows from Auto Loader, BEFORE good/bad "
        "split. Includes corrupted_record + rescued_data. Downstream tables "
        f"{TBL_QUARANTINE} and {TBL_RAW} consume this."
    ),
    cluster_by_auto=True,
)
def raw_xml_payload():
    return (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "xml")
        .option("rowTag", ROW_TAG)
        .option("rowValidationXSDPath", XML_XSD_SCHEMA_PYLD_PATH)
        .option("columnNameOfCorruptRecord", "corrupted_record")
        .option("rescuedDataColumn", "rescued_data")
        .option("mode", "PERMISSIVE")
        .schema(XML_PYLD_SCHEMA)
        .load(LANDING_PATH)
        .withColumn("file_path", F.col("_metadata.file_path"))
        .withColumn("file_name", F.col("_metadata.file_name"))
        .withColumn(
            "_file_modification_time",
            F.col("_metadata.file_modification_time"),
        )
        .withColumn("_ingested_at", F.current_timestamp())
    )


# --------------------------------------------------------------------------
# Table 2 of 3: {prefix}_quarantine (PUBLIC)
#
# Bad rows from raw_xml_payload (corrupted_record IS NOT NULL),
# enriched with a verbose XSD-validation error from the singleton-
# cached lxml UDF. Public so Ops / data stewards can triage without
# touching pipeline internals.
# --------------------------------------------------------------------------


@dp.table(
    name=TBL_QUARANTINE,
    comment=(
        "Public: malformed XML rows that failed Auto Loader XSD validation, "
        "enriched with xsd_validation_result (human-readable lxml error)."
    ),
    cluster_by_auto=True,
)
def quarantine():
    return (
        spark.readStream.table(TBL_RAW_XML_PAYLOAD)
        .filter(F.col("corrupted_record").isNotNull())
        .withColumn(
            "xsd_validation_result",
            xsd_error(F.col("corrupted_record"), F.lit(XML_XSD_SCHEMA_PYLD_PATH)),
        )
        .select(
            "file_path",
            "file_name",
            "_file_modification_time",
            "_ingested_at",
            "corrupted_record",
            "rescued_data",
            "xsd_validation_result",
        )
    )


# --------------------------------------------------------------------------
# Table 3 of 3: {prefix}_raw (PUBLIC — drop-in for the flatten notebook)
#
# Self-joins payload rows with their per-file header metadata, deriving
# BOTH sides from a single readStream of raw_xml_payload. This mirrors
# the legacy notebook's pattern (where both join sides came from the
# same streaming source) and avoids the cross-flow coordination issue
# we hit with a separate file_hdr_metadata streaming table — emit on
# the first triggered run, not the second.
#
# The header subquery deduplicates on file_path so the lxml UDF fires
# once per file per trigger, then applies from_xml and the filename
# regex (FileBatchIndex / FileBatchSize / FileVersion / ESMADate).
#
# Output preserves the column contract consumed by
# src/notebooks/2_flatten_explode_table.py.
# --------------------------------------------------------------------------


@dp.table(
    name=TBL_RAW,
    comment=(
        "Public: per-row payload joined with per-file header metadata "
        "(extracted via lxml from the source XML). Drop-in replacement "
        "for the output of the legacy 1_xml_file_loader_body.py notebook; "
        "consumed by the flatten step."
    ),
    cluster_by_auto=True,
)
def raw():
    payload = (
        spark.readStream.table(TBL_RAW_XML_PAYLOAD)
        .filter(F.col("corrupted_record").isNull())
    )

    headers = (
        payload.select("file_path", "file_name", "_file_modification_time")
        .dropDuplicates(["file_path"])
        .select(
            "file_path",
            "file_name",
            "_file_modification_time",
            extract_hdr_pyld_metadata_udf(
                F.col("file_path"), F.lit(ROW_TAG)
            ).alias("_hdr_xml"),
        )
        .withColumn(
            "hdr_pyld_metadata",
            F.from_xml(F.col("_hdr_xml"), XML_HDR_PYLD_METADATA_SCHEMA),
        )
        .drop("_hdr_xml")
        .withColumn(
            "FileBatchIndex",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                1, 3,
            ),
        )
        .withColumn(
            "FileBatchSize",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                4, 3,
            ),
        )
        .withColumn(
            "FileVersion",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                8, 1,
            ),
        )
        .withColumn(
            "ESMADate",
            F.concat(
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    2, 2,
                ),
                F.lit("-"),
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    4, 2,
                ),
                F.lit("-"),
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    6, 2,
                ),
            ),
        )
    )

    # Right-side alias avoids duplicate file_path / file_name /
    # _file_modification_time columns after the inner join.
    headers_aliased = headers.select(
        F.col("file_path").alias("_hdr_file_path"),
        "hdr_pyld_metadata",
        "FileBatchIndex",
        "FileBatchSize",
        "FileVersion",
        "ESMADate",
    )

    return (
        payload.join(
            headers_aliased,
            payload["file_path"] == headers_aliased["_hdr_file_path"],
            "inner",
        )
        .drop("_hdr_file_path", "corrupted_record", "rescued_data")
    )
