"""ESMA XML Loader — Spark Declarative Pipeline.

Parameterized SDP source backing both the EMIR and MiFIR XML loader pipelines.
Reads XML files via Auto Loader, splits malformed rows into a quarantine table
enriched with an lxml XSD-validation error, and produces a public
``{prefix}_raw`` streaming table with payload + header metadata joined per file.

All inputs are supplied via ``spark.conf`` — see the bundle pipeline
``configuration`` block in ``resources/bundle.{emir,mifir}_resources.yml``.

Reference: docs/superpowers/specs/2026-05-11-sdp-xml-loader-design.md
"""

from __future__ import annotations

import json

from pyspark import pipelines as dp
from pyspark.sql import functions as F
from pyspark.sql.types import StringType, StructType

# --------------------------------------------------------------------------
# Pipeline configuration (set in resources/bundle.*_resources.yml under
# resources.pipelines.<name>.configuration). All values are resolved at
# import time so the @dp.table decorators can reference them.
# --------------------------------------------------------------------------

CATALOG = spark.conf.get("catalog")
RAW_SCHEMA = spark.conf.get("raw_schema")
TABLE_PREFIX = spark.conf.get("table_prefix")
LANDING_PATH = spark.conf.get("landing_path")
ROW_TAG = spark.conf.get("row_tag")
XML_SCHEMA_PYLD_PATH = spark.conf.get("xml_schema_pyld_path")
XML_SCHEMA_HDR_PYLD_METADATA_PATH = spark.conf.get("xml_schema_hdr_pyld_metadata_path")
XML_XSD_SCHEMA_PYLD_PATH = spark.conf.get("xml_xsd_schema_pyld_path")
WATERMARK_INTERVAL = spark.conf.get("watermark_interval", "15 minutes")

# Fully qualified table names — published to {catalog}.{raw_schema}.
TBL_RAW_XML_PAYLOAD = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_raw_xml_payload"
TBL_FILE_HDR_METADATA = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_file_hdr_metadata"
TBL_QUARANTINE = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_quarantine"
TBL_RAW = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_raw"


def _read_schema(file_path: str) -> StructType:
    """Load a Spark JSON schema file into a StructType.

    Ported from src/notebooks/1_xml_file_loader_body.py — schemas are
    pre-generated by the XSD-conversion notebook and live as JSON files
    in a UC Volume next to the source XSDs.
    """
    with open(file_path, "r") as f:
        return StructType.fromJson(json.loads(f.read()))


# Loaded once at pipeline-start.
XML_PYLD_SCHEMA: StructType = _read_schema(XML_SCHEMA_PYLD_PATH)
XML_HDR_PYLD_METADATA_SCHEMA: StructType = _read_schema(XML_SCHEMA_HDR_PYLD_METADATA_PATH)


# --------------------------------------------------------------------------
# XSD-validation UDF (used by the quarantine table only).
#
# The XSD schema object is compiled once per Python worker per XSD path
# via _xsd_cache — Auto Loader's per-row XSD validation already runs
# upstream; this UDF only fires on the small minority of rows that
# already failed validation, where we want a human-readable error to
# surface in the quarantine table.
# --------------------------------------------------------------------------

_xsd_cache: dict = {}


def _get_xsd_schema(xsd_path: str):
    """Compile and cache an lxml XMLSchema per path, once per worker."""
    if xsd_path not in _xsd_cache:
        from lxml import etree
        with open(xsd_path, "rb") as f:
            _xsd_cache[xsd_path] = etree.XMLSchema(etree.XML(f.read()))
    return _xsd_cache[xsd_path]


@F.udf(returnType=StringType())
def xsd_error(xml_str: str, xsd_path: str) -> str:
    """Return a verbose XSD-validation error message, or 'XML is valid'."""
    from lxml import etree
    try:
        if xml_str is None:
            return "Invalid XML: input is null"
        schema = _get_xsd_schema(xsd_path)
        schema.assertValid(etree.fromstring(xml_str.encode("utf-8")))
        return "XML is valid"
    except Exception as e:
        return f"Invalid XML: {str(e)}"
