"""ESMA XML Loader (wholefile + explode variant) — for performance comparison.

Reads each XML file as a SINGLE Spark row (rowTag points at the document's
outer element, not <Stat>), then explodes the inner array of Stat elements
to produce the same final cardinality as the row-tag-based pipeline at
src/pipelines/xml_loader.py.

The point of this variant is to compare throughput against the streaming
row-tag approach: with wholefile reading, each Spark task ingests an
entire ~2 GB XML file in one shot, which trades parallelism for less
XML parser overhead per row. After the explode, the public-table column
contract matches src/pipelines/xml_loader.py exactly so downstream
consumers (flatten notebook) are unchanged.

All inputs are supplied via ``spark.conf`` — see the bundle pipeline
``configuration`` block in ``resources/bundle.emir_resources.yml``.
"""

from __future__ import annotations

import json

from pyspark import pipelines as dp
from pyspark.sql import functions as F
from pyspark.sql.types import StringType, StructType

# --------------------------------------------------------------------------
# Pipeline configuration (set in resources/bundle.emir_resources.yml under
# resources.pipelines.emir_xml_loader_pipeline_wholefile.configuration).
# Resolved at import time so the @dp.table decorators can reference them.
# --------------------------------------------------------------------------

CATALOG = spark.conf.get("catalog")
RAW_SCHEMA = spark.conf.get("raw_schema")
TABLE_PREFIX = spark.conf.get("table_prefix")
LANDING_PATH = spark.conf.get("landing_path")
# row_tag (= "Stat") is still used by the lxml header UDF to know where
# to stop iterating when extracting per-file header metadata.
ROW_TAG = spark.conf.get("row_tag")
# wholefile_row_tag is the OUTER document element (e.g. "BizData") — one
# Spark row per file when Auto Loader uses this as rowTag.
WHOLEFILE_ROW_TAG = spark.conf.get("wholefile_row_tag")
# stat_array_path is the dotted nested path from the wholefile-row-tag
# element down to the array of <Stat> elements, used as the argument
# to F.col(...) in explode(). E.g.
# "Pyld.Document.DerivsTradStatRpt.TradData.Stat".
STAT_ARRAY_PATH = spark.conf.get("stat_array_path")
XML_SCHEMA_PYLD_PATH = spark.conf.get("xml_schema_pyld_path")
XML_SCHEMA_HDR_PYLD_METADATA_PATH = spark.conf.get("xml_schema_hdr_pyld_metadata_path")
XML_XSD_SCHEMA_PYLD_PATH = spark.conf.get("xml_xsd_schema_pyld_path")
# Pipeline-config values are always strings; "true"/"false" toggles row-level
# XSD enforcement (rowValidationXSDPath) in raw_xml_file and the xsd_error
# UDF in quarantine. Default ON preserves production behavior.
ENABLE_XSD_VALIDATION = spark.conf.get("enable_xsd_validation", "true").lower() == "true"

# Fully qualified table names — note the _wholefile suffix to keep
# this experiment's tables separate from the row-tag pipeline's tables.
TBL_RAW_XML_FILE = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_raw_xml_file_wholefile"
TBL_QUARANTINE = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_quarantine_wholefile"
TBL_RAW = f"{CATALOG}.{RAW_SCHEMA}.{TABLE_PREFIX}_raw_wholefile"

# Filename-regex patterns used inside the inline self-join in `raw_wholefile`
# to extract FileBatchIndex / FileBatchSize / FileVersion / ESMADate from
# the source XML filename. Module-level so they're compiled once.
_FILE_INDEX_PATTERN = r"\d\d\d\d\d\d-\d"
_ESMA_DATE_PATTERN = r"-\d\d\d\d\d\d_"


def _read_schema(file_path: str) -> StructType:
    """Load a Spark JSON schema file into a StructType.

    Ported from src/notebooks/1_xml_file_loader_body.py — schemas are
    pre-generated by the XSD-conversion notebook and live as JSON files
    in a UC Volume next to the source XSDs.
    """
    with open(file_path, "r") as f:
        return StructType.fromJson(json.loads(f.read()))


# Loaded once at pipeline-start. The pyld schema is the per-Stat row schema
# (NOT the full-document schema). For the wholefile read we let Spark
# infer the deep nested document schema via cloudFiles.inferColumnTypes,
# then drill into it via STAT_ARRAY_PATH to grab the same per-Stat shape.
XML_HDR_PYLD_METADATA_SCHEMA: StructType = _read_schema(XML_SCHEMA_HDR_PYLD_METADATA_PATH)


# --------------------------------------------------------------------------
# XSD-validation UDF (used by the quarantine table only).
#
# The XSD schema object is compiled once per Python worker per XSD path
# via _xsd_cache — Auto Loader's per-row XSD validation already runs
# upstream; this UDF only fires on the small minority of rows that
# already failed validation, where we want a human-readable error to
# surface in the quarantine table.
# --------------------------------------------------------------------------

_xsd_cache: dict = {}


def _get_xsd_schema(xsd_path: str):
    """Compile and cache an lxml XMLSchema per path, once per worker."""
    if xsd_path not in _xsd_cache:
        from lxml import etree
        with open(xsd_path, "rb") as f:
            _xsd_cache[xsd_path] = etree.XMLSchema(etree.XML(f.read()))
    return _xsd_cache[xsd_path]


@F.udf(returnType=StringType())
def xsd_error(xml_str: str, xsd_path: str) -> str:
    """Return a verbose XSD-validation error message, or 'XML is valid'."""
    from lxml import etree
    try:
        if xml_str is None:
            return "Invalid XML: input is null"
        schema = _get_xsd_schema(xsd_path)
        schema.assertValid(etree.fromstring(xml_str.encode("utf-8")))
        return "XML is valid"
    except Exception as e:
        return f"Invalid XML: {str(e)}"


# --------------------------------------------------------------------------
# Header-extraction UDF.
#
# Reads the XML file via lxml.iterparse, stops at the first row-tag
# element, strips empty elements, and returns the header-only XML as a
# string. Lenient on failure (returns None) — preserving today's
# notebook behavior. Same UDF used in src/pipelines/xml_loader.py.
# --------------------------------------------------------------------------


def _strip_namespace(tag: str) -> str:
    """Strip ``{ns}name`` prefix from an lxml tag."""
    return tag.split("}")[-1] if "}" in tag else tag


def _remove_empty_elements(element) -> bool:
    """Recursively drop elements that have no children, attributes, or text."""
    children_to_remove = []
    for child in list(element):
        if _remove_empty_elements(child):
            children_to_remove.append(child)
    for child in children_to_remove:
        element.remove(child)
    has_children = len(list(element)) > 0
    has_attributes = bool(element.attrib)
    has_meaningful_text = (
        (element.text and element.text.strip())
        or (element.tail and element.tail.strip())
    )
    return not has_children and not has_attributes and not has_meaningful_text


def _extract_hdr_pyld_metadata(file_path: str, row_tag: str) -> str | None:
    """Return the header-only XML for a single file, stopping at row_tag."""
    from lxml import etree
    try:
        context = etree.iterparse(file_path, events=("start", "end"), recover=True)
        element_stack = []
        skip_depth = 0
        root = None
        found_row_tag = False

        for event, elem in context:
            tag_name = _strip_namespace(elem.tag)
            if event == "start":
                if tag_name == row_tag and not found_row_tag:
                    found_row_tag = True
                    elem.clear()
                    break
                should_skip = (skip_depth > 0) or (tag_name == row_tag)
                if should_skip:
                    skip_depth += 1
                else:
                    new_elem = etree.Element(elem.tag, attrib=elem.attrib)
                    new_elem.tag = _strip_namespace(new_elem.tag)
                    if element_stack:
                        element_stack[-1].append(new_elem)
                    else:
                        root = new_elem
                    element_stack.append(new_elem)
            elif event == "end":
                if skip_depth > 0:
                    skip_depth -= 1
                elif element_stack:
                    current_elem = element_stack.pop()
                    current_elem.text = elem.text
                    current_elem.tail = elem.tail
                elem.clear()

        if root is not None:
            _remove_empty_elements(root)
            return etree.tostring(root, encoding="unicode", pretty_print=True)
        return None
    except Exception as e:
        # Lenient: failure surfaces as null hdr_pyld_metadata downstream.
        print(f"Error processing {file_path}: {e}")
        return None


extract_hdr_pyld_metadata_udf = F.udf(_extract_hdr_pyld_metadata, StringType())


# --------------------------------------------------------------------------
# Table 1 of 3: {prefix}_raw_xml_file_wholefile (intermediate — internal)
#
# Auto Loader reads each XML file as ONE row (rowTag = document root).
# The full nested document, including the TradData.Stat array, lands as
# a deeply nested struct column. Schema is inferred via
# cloudFiles.inferColumnTypes — the inferred schema is cached in the
# pipeline's storage so inference only fires for newly seen file shapes.
# Pre-supplying a hand-rolled full-document schema is the obvious
# follow-up optimization once we've measured the inference cost.
# --------------------------------------------------------------------------


@dp.table(
    name=TBL_RAW_XML_FILE,
    comment=(
        "Internal: one row per source XML file (rowTag = document root). "
        "Contains the full nested document as a struct, including the "
        f"TradData.Stat array. Exploded downstream in {TBL_RAW}."
    ),
    cluster_by_auto=True,
)
def raw_xml_file():
    loader = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "xml")
        .option("rowTag", WHOLEFILE_ROW_TAG)  # outer element, not Stat
        .option("columnNameOfCorruptRecord", "corrupted_record")
        .option("rescuedDataColumn", "rescued_data")
        .option("mode", "PERMISSIVE")
        .option("cloudFiles.inferColumnTypes", "true")
        .option("cloudFiles.schemaEvolutionMode", "addNewColumns")
    )
    if ENABLE_XSD_VALIDATION:
        loader = loader.option("rowValidationXSDPath", XML_XSD_SCHEMA_PYLD_PATH)
    return (
        loader
        .load(LANDING_PATH)
        .withColumn("file_path", F.col("_metadata.file_path"))
        .withColumn("file_name", F.col("_metadata.file_name"))
        .withColumn(
            "_file_modification_time",
            F.col("_metadata.file_modification_time"),
        )
        .withColumn("_ingested_at", F.current_timestamp())
    )


# --------------------------------------------------------------------------
# Table 2 of 3: {prefix}_quarantine_wholefile (PUBLIC)
#
# Whole-file rows from raw_xml_file_wholefile that Auto Loader couldn't
# parse (corrupted_record IS NOT NULL), enriched with a verbose
# XSD-validation error from the singleton-cached lxml UDF.
#
# When ENABLE_XSD_VALIDATION is False, the xsd_error UDF is skipped and
# xsd_validation_result is the literal "XSD validation disabled".
# --------------------------------------------------------------------------


@dp.table(
    name=TBL_QUARANTINE,
    comment=(
        "Public: malformed XML FILES (whole-file rowTag failed to parse). "
        "Includes xsd_validation_result when ENABLE_XSD_VALIDATION is on."
    ),
    cluster_by_auto=True,
)
def quarantine_wholefile():
    bad = (
        spark.readStream.table(TBL_RAW_XML_FILE)
        .filter(F.col("corrupted_record").isNotNull())
    )
    if ENABLE_XSD_VALIDATION:
        bad = bad.withColumn(
            "xsd_validation_result",
            xsd_error(F.col("corrupted_record"), F.lit(XML_XSD_SCHEMA_PYLD_PATH)),
        )
    else:
        bad = bad.withColumn(
            "xsd_validation_result",
            F.lit("XSD validation disabled"),
        )
    return bad.select(
        "file_path",
        "file_name",
        "_file_modification_time",
        "_ingested_at",
        "corrupted_record",
        "rescued_data",
        "xsd_validation_result",
    )


# --------------------------------------------------------------------------
# Table 3 of 3: {prefix}_raw_wholefile (PUBLIC — mirrors emir_raw shape)
#
# Explodes the TradData.Stat array (one Stat element per output row),
# joins with per-file header metadata via the same lxml UDF + filename
# regex used by the row-tag pipeline. Cardinality should match the
# row-tag pipeline's emir_raw exactly.
# --------------------------------------------------------------------------


@dp.table(
    name=TBL_RAW,
    comment=(
        "Public: per-Stat-row payload joined with per-file header metadata. "
        "Built by exploding TradData.Stat in the wholefile read. Cardinality "
        "should match the row-tag pipeline's emir_raw exactly."
    ),
    cluster_by_auto=True,
)
def raw_wholefile():
    files = (
        spark.readStream.table(TBL_RAW_XML_FILE)
        .filter(F.col("corrupted_record").isNull())
    )

    # Per-file header — extract via lxml UDF on file_path (one call per
    # file since we already have one row per file at this point — no
    # dropDuplicates needed unlike the row-tag pipeline).
    headers = (
        files.select(
            "file_path",
            "file_name",
            "_file_modification_time",
            extract_hdr_pyld_metadata_udf(
                F.col("file_path"), F.lit(ROW_TAG)
            ).alias("_hdr_xml"),
        )
        .withColumn(
            "hdr_pyld_metadata",
            F.from_xml(F.col("_hdr_xml"), XML_HDR_PYLD_METADATA_SCHEMA),
        )
        .drop("_hdr_xml")
        .withColumn(
            "FileBatchIndex",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                1, 3,
            ),
        )
        .withColumn(
            "FileBatchSize",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                4, 3,
            ),
        )
        .withColumn(
            "FileVersion",
            F.substring(
                F.regexp_extract(F.col("file_name"), _FILE_INDEX_PATTERN, 0),
                8, 1,
            ),
        )
        .withColumn(
            "ESMADate",
            F.concat(
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    2, 2,
                ),
                F.lit("-"),
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    4, 2,
                ),
                F.lit("-"),
                F.substring(
                    F.regexp_extract(F.col("file_name"), _ESMA_DATE_PATTERN, 0),
                    6, 2,
                ),
            ),
        )
    )

    # Explode the Stat array. STAT_ARRAY_PATH is a dotted nested-struct
    # path like "Pyld.Document.DerivsTradStatRpt.TradData.Stat" — F.col()
    # navigates nested structs via the same dotted notation. After
    # explode + Stat.* the schema matches the per-row pipeline's payload.
    exploded = (
        files.select(
            "file_path",
            "file_name",
            "_file_modification_time",
            "_ingested_at",
            F.explode(F.col(STAT_ARRAY_PATH)).alias("Stat"),
        )
        .select(
            "file_path",
            "file_name",
            "_file_modification_time",
            "_ingested_at",
            F.col("Stat.*"),
        )
    )

    # Self-join exploded rows with their per-file headers. Right-side
    # alias avoids duplicate column names after the join. Same shape as
    # the row-tag pipeline's emir_raw.
    headers_aliased = headers.select(
        F.col("file_path").alias("_hdr_file_path"),
        "hdr_pyld_metadata",
        "FileBatchIndex",
        "FileBatchSize",
        "FileVersion",
        "ESMADate",
    )

    return (
        exploded.join(
            headers_aliased,
            exploded["file_path"] == headers_aliased["_hdr_file_path"],
            "inner",
        )
        .drop("_hdr_file_path")
    )
