# Databricks notebook source
# MAGIC %md
# MAGIC # XML File Ingestion Pipeline
# MAGIC 
# MAGIC This notebook ingests regulatory XML files from cloud storage into Delta Lake tables using structured streaming. Regulatory bodies (ESMA, EMIR, MiFIR) deliver transaction reports as large XML files with complex nested structures, requiring robust processing capabilities.
# MAGIC 
# MAGIC The pipeline uses Databricks Auto Loader (cloudFiles) to incrementally process XML files as they arrive, applies XSD validation to ensure data quality, and extracts header metadata separately from business payloads. This separation enables efficient querying and compliance reporting by allowing you to query metadata without scanning large payload data. Streaming ingestion ensures reliable processing of high-volume data while maintaining exactly-once semantics through checkpointing.
# MAGIC 
# MAGIC **Notice:** This code is shared as a guide and should not be deployed directly into production on Databricks without proper testing and configuration.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Install Required Libraries
# MAGIC 
# MAGIC Install the `lxml` library for efficient XML parsing. This library is used in the custom UDF that extracts header metadata from XML files.

# COMMAND ----------

# MAGIC %pip install lxml

# COMMAND ----------

from pyspark.errors import PySparkException
from pyspark.sql.functions import col, current_timestamp, regexp_extract, substring, concat, lit, udf, from_xml
from pyspark.sql.types import StringType, StructType
from pyspark.sql import DataFrame
import json

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration Parameters
# MAGIC 
# MAGIC Configure the ingestion pipeline by setting catalog locations, file paths, and processing options:
# MAGIC 
# MAGIC - `catalog` / `raw_schema`: Unity Catalog location for raw tables
# MAGIC - `xml_schema_*_path`: JSON schemas generated by the XSD processing notebook (used for type-safe XML parsing)
# MAGIC - `landing_path`: Source directory where XML files arrive from regulatory bodies
# MAGIC - `checkpoint_path`: Location for streaming checkpoints (ensures exactly-once processing and enables recovery from failures)
# MAGIC - `row_tag`: XML element that represents a single row (e.g., "Stat" for EMIR statements, "Tx" for transactions)
# MAGIC 
# MAGIC Adjust these parameters based on your Unity Catalog structure and storage locations before running the notebook.

# COMMAND ----------

dbutils.widgets.text("catalog","esma")
dbutils.widgets.text("raw_schema","emir_raw")

dbutils.widgets.text("xml_schema_pyld_path","/Volumes/esma/default/regulatory_data/schemas/emir/pyld_schema.json")
dbutils.widgets.text("xml_schema_hdr_pyld_metadata_path","/Volumes/esma/default/regulatory_data/schemas/emir/hdr_pyld_metadata_schema.json")
dbutils.widgets.text("xml_xsd_schema_pyld_path","/Volumes/esma/default/regulatory_data/schemas/emir/row_tag_schema.xsd")

dbutils.widgets.text("landing_path", "/Volumes/esma/default/regulatory_data/emir/landing/")
dbutils.widgets.text("checkpoint_path", "/Volumes/esma/default/regulatory_data/emir/checkpoints/")
dbutils.widgets.text("processed_path", "/Volumes/esma/default/regulatory_data/emir/processed/")

dbutils.widgets.text("files_per_trigger", "16")
dbutils.widgets.text("row_tag", "Stat")

dbutils.widgets.text("table_prefix", "emir_")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Retrieve Parameters
# MAGIC 
# MAGIC Retrieve widget values and convert them to Python variables used throughout the notebook.

# COMMAND ----------

catalog = dbutils.widgets.get("catalog")
raw_schema = dbutils.widgets.get("raw_schema")

xml_schema_pyld_path = dbutils.widgets.get("xml_schema_pyld_path")
xml_schema_hdr_pyld_metadata_path = dbutils.widgets.get("xml_schema_hdr_pyld_metadata_path")
xml_xsd_schema_pyld_path = dbutils.widgets.get("xml_xsd_schema_pyld_path")

landing_path = dbutils.widgets.get("landing_path")
checkpoint_path = dbutils.widgets.get("checkpoint_path")
processed_path = dbutils.widgets.get("processed_path")

files_per_trigger = int(dbutils.widgets.get("files_per_trigger"))
row_tag = dbutils.widgets.get("row_tag")

table_prefix = dbutils.widgets.get("table_prefix")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Load JSON Schemas
# MAGIC 
# MAGIC Load the JSON schemas created by the XSD processing notebook into Spark StructType objects. Schemas enable type-safe XML parsing and automatic column creation in Spark DataFrames, while avoiding the overhead of schema inference.
# MAGIC 
# MAGIC Using predefined schemas improves performance and ensures consistent data types across pipeline runs. The function reads each JSON schema file and converts it to a Spark StructType that the XML reader can use for parsing.

# COMMAND ----------

def readSchema(file: str) -> StructType:
    """
    Reads a JSON schema from a file and returns a Spark StructType object.

    Args:
        file (str): Path to the JSON schema file.

    Returns:
        StructType: Spark schema object parsed from the JSON file.
    """
    with open(file, 'r') as f:
        schema_json = f.read()
    schema = StructType.fromJson(json.loads(schema_json))
    return schema

# COMMAND ----------

xml_pyld_schema = readSchema(xml_schema_pyld_path)
xml_hdr_pyld_metadata_schema = readSchema(xml_schema_hdr_pyld_metadata_path)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configure Auto Loader XML Stream
# MAGIC 
# MAGIC Create a streaming DataFrame that reads XML files from cloud storage using Auto Loader. This configuration automatically tracks which files have been processed, handles new file arrivals, and provides exactly-once processing guarantees.
# MAGIC 
# MAGIC The cloudFiles format is configured with XML-specific options: the row tag defines record boundaries (each `<Stat>` or `<Tx>` element becomes a row), XSD validation catches malformed XML early, and PERMISSIVE mode with rescued data columns preserves unparseable records for later analysis. When an XML file arrives in the landing path, Auto Loader parses each element matching the row tag and validates it against the XSD, handling any schema mismatches gracefully.

# COMMAND ----------

#TODO: Add cloudFiles.cleanSource and cloudFiles.moveDestination

raw_pyld_df = (
    spark.readStream.format("cloudFiles")
    .option("cloudFiles.format", "xml")
    .option("rowTag", row_tag)
    .option("rowValidationXSDPath", xml_xsd_schema_pyld_path)
    .option("columnNameOfCorruptRecord","corrupted_record")
    .option("rescuedDataColumn", "rescued_data")
    .option("mode", "PERMISSIVE")
    # .option("cloudFiles.maxFilesPerTrigger", files_per_trigger)
    .schema(xml_pyld_schema)
    .load(landing_path)            
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Extract Header and Metadata from XML Files
# MAGIC 
# MAGIC Define a UDF that extracts document headers and metadata while excluding payload data records. Regulatory XML files contain both control information (sender, timestamps, file batching) and business data (transactions, statements). Separating these enables efficient metadata queries without scanning large payload tables, which is particularly important for data lineage and audit trails.
# MAGIC 
# MAGIC The UDF uses streaming XML parsing (lxml iterparse) to read each file until it reaches the first row tag element, capturing only the header portion. This approach avoids loading entire large XML files into memory, making it efficient even for files with millions of transaction records.

# COMMAND ----------

from lxml import etree
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType

def strip_namespace(tag: str) -> str:
    """Remove XML namespace from tag."""
    return tag.split('}')[-1] if '}' in tag else tag

def remove_empty_elements(element):
    children_to_remove = []
    for child in list(element):
        if remove_empty_elements(child):
            children_to_remove.append(child)
    for child in children_to_remove:
        element.remove(child)
    has_children = len(list(element)) > 0
    has_attributes = bool(element.attrib)
    has_meaningful_text = (element.text and element.text.strip()) or (element.tail and element.tail.strip())
    is_completely_empty = not has_children and not has_attributes and not has_meaningful_text
    return is_completely_empty

def extract_hdr_pyld_metadata(file_path: str, row_tag: str = "Stat") -> str:
    try:
        context = etree.iterparse(file_path, events=("start", "end"), recover=True)
        element_stack = []
        skip_depth = 0
        root = None
        found_row_tag = False
        
        for event, elem in context:
            tag_name = strip_namespace(elem.tag)
            
            if event == "start":
                if tag_name == row_tag and not found_row_tag:
                    found_row_tag = True
                    elem.clear()
                    break
                should_skip = (skip_depth > 0) or (tag_name == row_tag)
                if should_skip:
                    skip_depth += 1
                else:
                    new_elem = etree.Element(elem.tag, attrib=elem.attrib)
                    new_elem.tag = strip_namespace(new_elem.tag)

                    if element_stack:
                        element_stack[-1].append(new_elem)
                    else:
                        root = new_elem
                    element_stack.append(new_elem)
            elif event == "end":
                if skip_depth > 0:
                    skip_depth -= 1
                else:
                    if element_stack:
                        current_elem = element_stack.pop()
                        current_elem.text = elem.text
                        current_elem.tail = elem.tail
                elem.clear()
        
        if root is not None:
            remove_empty_elements(root)
            return etree.tostring(root, encoding="unicode", pretty_print=True)
        return None
        
    except Exception as e:
        print(f"Error processing {file_path}: {str(e)}")
        return None

extract_hdr_pyld_metadata_udf = udf(extract_hdr_pyld_metadata, StringType())

# COMMAND ----------

# MAGIC %md
# MAGIC ## Add File Metadata Columns
# MAGIC 
# MAGIC Enrich the streaming DataFrame with Auto Loader metadata including file path, file name, and ingestion timestamp. This file-level metadata enables traceability, debugging, and reprocessing of specific files if needed. The `inserted_at` timestamp tracks when data entered the system, which is valuable for audit purposes and understanding data freshness.

# COMMAND ----------

raw_pyld_df = (
  raw_pyld_df
  .withColumn("source_metadata", col("_metadata"))
  .withColumn("file_path", col("source_metadata.file_path"))
  .withColumn("file_name", col("source_metadata.file_name"))
  .withColumn("inserted_at", current_timestamp())
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Extract and Parse Header Metadata
# MAGIC 
# MAGIC Call the metadata extraction UDF on each unique file and parse the resulting XML string into structured columns. Processing metadata once per file (rather than per row) is more efficient since the header is the same for all rows in a file.
# MAGIC 
# MAGIC The process gets distinct file paths from the stream, extracts the header XML for each file, then uses the `from_xml` function to convert XML strings into Spark structs. This makes header fields directly queryable as DataFrame columns.

# COMMAND ----------

distinct_file_paths_df = raw_pyld_df.select("file_path", "file_name").distinct()
hdr_pyld_metadata_df = (distinct_file_paths_df.withColumn(
  "hdr_pyld_metadata", 
  from_xml(
    extract_hdr_pyld_metadata_udf(col("file_path"), lit(row_tag)), 
    xml_hdr_pyld_metadata_schema
    )
  )
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Extract File Naming Convention Metadata
# MAGIC 
# MAGIC Parse structured information from XML filenames using regex patterns. ESMA regulatory files follow naming conventions that encode batch information, version numbers, and submission dates. Extracting these fields enables you to track file processing completeness (have all files in a batch arrived?), identify resubmissions (version numbers), and organize data by submission date.
# MAGIC 
# MAGIC The regex patterns extract batch index, batch size, file version, and ESMA date from filenames. For example, a filename like `EMIR_123456_001-100-1_20231015.xml` indicates file 1 of 100 in batch 123456, version 1, submitted on October 15, 2023.

# COMMAND ----------

#TODO: Join hdr_pyld_metadata_df with the table that contains file_name and zip_name to run regex on that before the join

file_index_pattern = r"\d\d\d\d\d\d-\d"
esma_date_pattern = r"-\d\d\d\d\d\d_"

hdr_pyld_mtdt_rgx_df = (hdr_pyld_metadata_df
    .withColumn(
        "FileBatchIndex",
        substring(regexp_extract(col("file_name"), file_index_pattern, 0),1,3)
    )
    .withColumn(
        "FileBatchSize",
        substring(regexp_extract(col("file_name"), file_index_pattern, 0),4,3)
    )
    .withColumn(
        "FileVersion",
        substring(regexp_extract(col("file_name"), file_index_pattern, 0),8,1)
    )
    .withColumn(
        "ESMADate",
        concat(
            substring(regexp_extract(col("file_name"), esma_date_pattern, 0), 2, 2), lit('-'),
            substring(regexp_extract(col("file_name"), esma_date_pattern, 0), 4, 2), lit('-'),
            substring(regexp_extract(col("file_name"), esma_date_pattern, 0), 6, 2)
        )
    )
).drop("file_name")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Join Metadata with Payload Data
# MAGIC 
# MAGIC Combine the payload records with their corresponding file-level header and metadata. Each payload record needs its source file context for traceability and regulatory reporting. This enrichment allows you to run queries that filter by submission date, file batch, sender information, or other metadata fields without having to reference separate tables.

# COMMAND ----------

hdr_pyld_df = raw_pyld_df.join(hdr_pyld_mtdt_rgx_df, on="file_path")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Define Output Table and Checkpoint Paths
# MAGIC 
# MAGIC Set the destination table name and checkpoint location for the streaming write. The checkpoint tracks processing progress and enables recovery from failures.

# COMMAND ----------

raw_table = f"{table_prefix}_raw"
raw_table_checkpoint = f"{checkpoint_path}/{raw_table}_raw_table_checkpoint"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Write to Delta Raw Table
# MAGIC 
# MAGIC Stream the enriched XML data into a Delta Lake table with checkpointing for reliable ingestion. Delta Lake provides ACID transactions, time travel, and schema evolution capabilities that are essential for production data pipelines.
# MAGIC 
# MAGIC Checkpointing ensures exactly-once processing - if the job fails or is stopped, it resumes from the last successful batch without reprocessing or missing data. The `availableNow` trigger processes all available data then stops, making it ideal for scheduled jobs rather than continuously running streams. The notebook creates the catalog and schema if they don't exist, then writes the streaming DataFrame to Delta format with append mode.

# COMMAND ----------

spark.sql(f"CREATE CATALOG IF NOT EXISTS {catalog}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{raw_schema}")

# COMMAND ----------

try:
  (hdr_pyld_df.writeStream
    .trigger(availableNow=True)
    .format("delta")
    .outputMode("append")
    .option("checkpointLocation", raw_table_checkpoint) 
    .toTable(f"{catalog}.{raw_schema}.{raw_table}")
  )

except PySparkException as ex:
  print("Error Class       : " + ex.getErrorClass())
  print("Message parameters: " + str(ex.getMessageParameters()))
  print("SQLSTATE          : " + ex.getSqlState())
  print(ex)
