# Databricks notebook source
# MAGIC %md
# MAGIC # XML File Ingestion Pipeline
# MAGIC 
# MAGIC ## What
# MAGIC This notebook ingests regulatory XML files from cloud storage into Delta Lake tables using structured streaming. It parses XML documents, extracts header and payload metadata, and writes to a raw Delta table for downstream processing.
# MAGIC 
# MAGIC ## Why
# MAGIC Regulatory bodies (ESMA, EMIR, MiFIR) deliver transaction reports as large XML files with complex nested structures. Streaming ingestion ensures reliable processing of high-volume data while maintaining exactly-once semantics. Separating header metadata from business payloads enables efficient querying and compliance reporting.
# MAGIC 
# MAGIC ## How
# MAGIC The pipeline uses Databricks Auto Loader (cloudFiles) to incrementally process XML files, applies XSD validation, extracts metadata using custom UDFs, and writes to Delta tables with checkpointing for fault tolerance.
# MAGIC 
# MAGIC **Notice:** This code is shared as a guide and should not be deployed directly into production on Databricks without proper testing and configuration.

# COMMAND ----------

# MAGIC %md
# MAGIC ## Install Required Libraries
# MAGIC 
# MAGIC Install `lxml` for efficient XML parsing in the metadata extraction UDF.

# COMMAND ----------

# MAGIC %pip install lxml

# COMMAND ----------

from pyspark.errors import PySparkException
from pyspark.sql.functions import col, current_timestamp, regexp_extract, substring, concat, lit, udf, from_xml
from pyspark.sql.types import StringType, StructType
from pyspark.sql import DataFrame
import json

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration Parameters
# MAGIC 
# MAGIC **What:** Define catalog, schema, paths, and processing options for the ingestion pipeline
# MAGIC 
# MAGIC **Key Parameters:**
# MAGIC - `catalog` / `raw_schema`: Unity Catalog location for raw tables
# MAGIC - `xml_schema_*_path`: JSON schemas generated by the XSD processing notebook
# MAGIC - `landing_path`: Source directory where XML files arrive
# MAGIC - `checkpoint_path`: Location for streaming checkpoints (ensures exactly-once processing)
# MAGIC - `row_tag`: XML element that represents a single row (e.g., "Stat" for EMIR statements)

# COMMAND ----------

dbutils.widgets.text("catalog","esma")
dbutils.widgets.text("raw_schema","emir_raw")

dbutils.widgets.text("xml_schema_pyld_path","/Volumes/esma/default/regulatory_data/schemas/emir/pyld_schema.json")
dbutils.widgets.text("xml_schema_hdr_pyld_metadata_path","/Volumes/esma/default/regulatory_data/schemas/emir/hdr_pyld_metadata_schema.json")
dbutils.widgets.text("xml_xsd_schema_pyld_path","/Volumes/esma/default/regulatory_data/schemas/emir/row_tag_schema.xsd")

dbutils.widgets.text("landing_path", "/Volumes/esma/default/regulatory_data/emir/landing/")
dbutils.widgets.text("checkpoint_path", "/Volumes/esma/default/regulatory_data/emir/checkpoints/")
dbutils.widgets.text("processed_path", "/Volumes/esma/default/regulatory_data/emir/processed/")

dbutils.widgets.text("files_per_trigger", "16")
dbutils.widgets.text("row_tag", "Stat")

dbutils.widgets.text("table_prefix", "emir_")

# COMMAND ----------

# MAGIC %md
# MAGIC ### Retrieve Parameters
# MAGIC 
# MAGIC Parse widget values into Python variables for use throughout the notebook.

# COMMAND ----------

catalog = dbutils.widgets.get("catalog")
raw_schema = dbutils.widgets.get("raw_schema")

xml_schema_pyld_path = dbutils.widgets.get("xml_schema_pyld_path")
xml_schema_hdr_pyld_metadata_path = dbutils.widgets.get("xml_schema_hdr_pyld_metadata_path")
xml_xsd_schema_pyld_path = dbutils.widgets.get("xml_xsd_schema_pyld_path")

landing_path = dbutils.widgets.get("landing_path")
checkpoint_path = dbutils.widgets.get("checkpoint_path")
processed_path = dbutils.widgets.get("processed_path")

files_per_trigger = int(dbutils.widgets.get("files_per_trigger"))
row_tag = dbutils.widgets.get("row_tag")

table_prefix = dbutils.widgets.get("table_prefix")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Load JSON Schemas
# MAGIC 
# MAGIC **What:** Load the JSON schemas created by the XSD processing notebook
# MAGIC 
# MAGIC **Why:** Schemas enable type-safe XML parsing and automatic column creation in Spark DataFrames. Using predefined schemas improves performance by avoiding schema inference and ensures consistent data types across pipeline runs.
# MAGIC 
# MAGIC **How:** Read JSON schema files and convert them to Spark StructType objects used by the XML reader.

# COMMAND ----------

def readSchema(file: str) -> StructType:
    """
    Reads a JSON schema from a file and returns a Spark StructType object.

    Args:
        file (str): Path to the JSON schema file.

    Returns:
        StructType: Spark schema object parsed from the JSON file.
    """
    with open(file, 'r') as f:
        schema_json = f.read()
    schema = StructType.fromJson(json.loads(schema_json))
    return schema

# COMMAND ----------

xml_pyld_schema = readSchema(xml_schema_pyld_path)
xml_hdr_pyld_metadata_schema = readSchema(xml_schema_hdr_pyld_metadata_path)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configure Auto Loader XML Stream
# MAGIC 
# MAGIC **What:** Create a streaming DataFrame that reads XML files from cloud storage using Auto Loader
# MAGIC 
# MAGIC **Why:** Auto Loader automatically tracks processed files, handles new file arrivals, and provides exactly-once processing guarantees. XSD validation catches malformed XML early, and PERMISSIVE mode captures corrupt records for analysis.
# MAGIC 
# MAGIC **How:** Configure cloudFiles format with XML options: row tag defines record boundaries, XSD path enables validation, and rescued data columns preserve unparseable records.
# MAGIC 
# MAGIC **Example:** When an XML file arrives in `landing_path`, Auto Loader parses each `<Stat>` element as a row, validates against XSD, and handles any schema mismatches gracefully.

# COMMAND ----------

#TODO: Add cloudFiles.cleanSource and cloudFiles.moveDestination

raw_pyld_df = (
    spark.readStream.format("cloudFiles")
    .option("cloudFiles.format", "xml")
    .option("rowTag", row_tag)
    .option("rowValidationXSDPath", xml_xsd_schema_pyld_path)
    .option("columnNameOfCorruptRecord","corrupted_record")
    .option("rescuedDataColumn", "rescued_data")
    .option("mode", "PERMISSIVE")
    # .option("cloudFiles.maxFilesPerTrigger", files_per_trigger)
    .schema(xml_pyld_schema)
    .load(landing_path)            
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Extract Header and Metadata from XML Files
# MAGIC 
# MAGIC **What:** Define a UDF that extracts document headers and metadata while excluding payload data records
# MAGIC 
# MAGIC **Why:** Regulatory XML files contain both control information (sender, timestamps, file batching) and business data (transactions). Separating these enables efficient metadata queries without scanning large payload tables. Header information is often needed for data lineage and audit trails.
# MAGIC 
# MAGIC **How:** The UDF uses streaming XML parsing (lxml iterparse) to read the file until it reaches the first row tag element, capturing only the header portion. This avoids loading entire large XML files into memory.

# COMMAND ----------

from lxml import etree
from pyspark.sql.functions import udf
from pyspark.sql.types import StringType

def strip_namespace(tag: str) -> str:
    """Remove XML namespace from tag."""
    return tag.split('}')[-1] if '}' in tag else tag

def remove_empty_elements(element):
    children_to_remove = []
    for child in list(element):
        if remove_empty_elements(child):
            children_to_remove.append(child)
    for child in children_to_remove:
        element.remove(child)
    has_children = len(list(element)) > 0
    has_attributes = bool(element.attrib)
    has_meaningful_text = (element.text and element.text.strip()) or (element.tail and element.tail.strip())
    is_completely_empty = not has_children and not has_attributes and not has_meaningful_text
    return is_completely_empty

def extract_hdr_pyld_metadata(file_path: str, row_tag: str = "Stat") -> str:
    try:
        context = etree.iterparse(file_path, events=("start", "end"), recover=True)
        element_stack = []
        skip_depth = 0
        root = None
        found_row_tag = False
        
        for event, elem in context:
            tag_name = strip_namespace(elem.tag)
            
            if event == "start":
                if tag_name == row_tag and not found_row_tag:
                    found_row_tag = True
                    elem.clear()
                    break
                should_skip = (skip_depth > 0) or (tag_name == row_tag)
                if should_skip:
                    skip_depth += 1
                else:
                    new_elem = etree.Element(elem.tag, attrib=elem.attrib)
                    new_elem.tag = strip_namespace(new_elem.tag)

                    if element_stack:
                        element_stack[-1].append(new_elem)
                    else:
                        root = new_elem
                    element_stack.append(new_elem)
            elif event == "end":
                if skip_depth > 0:
                    skip_depth -= 1
                else:
                    if element_stack:
                        current_elem = element_stack.pop()
                        current_elem.text = elem.text
                        current_elem.tail = elem.tail
                elem.clear()
        
        if root is not None:
            remove_empty_elements(root)
            return etree.tostring(root, encoding="unicode", pretty_print=True)
        return None
        
    except Exception as e:
        print(f"Error processing {file_path}: {str(e)}")
        return None

extract_hdr_pyld_metadata_udf = udf(extract_hdr_pyld_metadata, StringType())

# COMMAND ----------

# MAGIC %md
# MAGIC ## Add File Metadata Columns
# MAGIC 
# MAGIC **What:** Enrich the streaming DataFrame with Auto Loader metadata (file path, file name, ingestion timestamp)
# MAGIC 
# MAGIC **Why:** File-level metadata enables traceability, debugging, and reprocessing specific files if needed. The `inserted_at` timestamp tracks when data entered the system for audit purposes.

# COMMAND ----------

raw_pyld_df = (
  raw_pyld_df
  .withColumn("source_metadata", col("_metadata"))
  .withColumn("file_path", col("source_metadata.file_path"))
  .withColumn("file_name", col("source_metadata.file_name"))
  .withColumn("inserted_at", current_timestamp())
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Extract and Parse Header Metadata
# MAGIC 
# MAGIC **What:** Call the metadata extraction UDF on each unique file and parse the resulting XML string into structured columns
# MAGIC 
# MAGIC **Why:** Processing metadata once per file (not per row) is more efficient. The `from_xml` function converts XML strings into Spark structs, making header fields queryable.
# MAGIC 
# MAGIC **How:** Get distinct file paths from the stream, extract header XML for each file, then parse the XML using the metadata schema.

# COMMAND ----------

distinct_file_paths_df = raw_pyld_df.select("file_path", "file_name").distinct()
hdr_pyld_metadata_df = (distinct_file_paths_df.withColumn(
  "hdr_pyld_metadata", 
  from_xml(
    extract_hdr_pyld_metadata_udf(col("file_path"), lit(row_tag)), 
    xml_hdr_pyld_metadata_schema
    )
  )
)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Extract File Naming Convention Metadata
# MAGIC 
# MAGIC **What:** Parse structured information from XML filenames using regex patterns
# MAGIC 
# MAGIC **Why:** ESMA regulatory files follow naming conventions that encode batch information, version numbers, and submission dates. Extracting these fields enables tracking file processing completeness and identifying resubmissions.
# MAGIC 
# MAGIC **How:** Apply regex patterns to extract batch index, batch size, file version, and ESMA date from filenames.
# MAGIC 
# MAGIC **Example:** A filename like `EMIR_123456_001-100-1_20231015.xml` indicates file 1 of 100 in batch 123456, version 1, for October 15, 2023.

# COMMAND ----------

#TODO: Join hdr_pyld_metadata_df with the table that contains file_name and zip_name to run regex on that before the join

file_index_pattern = r"\d\d\d\d\d\d-\d"
esma_date_pattern = r"-\d\d\d\d\d\d_"

hdr_pyld_mtdt_rgx_df = (hdr_pyld_metadata_df
    .withColumn(
        "FileBatchIndex",
        substring(regexp_extract(col("file_name"), file_index_pattern, 0),1,3)
    )
    .withColumn(
        "FileBatchSize",
        substring(regexp_extract(col("file_name"), file_index_pattern, 0),4,3)
    )
    .withColumn(
        "FileVersion",
        substring(regexp_extract(col("file_name"), file_index_pattern, 0),8,1)
    )
    .withColumn(
        "ESMADate",
        concat(
            substring(regexp_extract(col("file_name"), esma_date_pattern, 0), 2, 2), lit('-'),
            substring(regexp_extract(col("file_name"), esma_date_pattern, 0), 4, 2), lit('-'),
            substring(regexp_extract(col("file_name"), esma_date_pattern, 0), 6, 2)
        )
    )
).drop("file_name")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Join Metadata with Payload Data
# MAGIC 
# MAGIC **What:** Combine the payload records with their corresponding file-level header and metadata
# MAGIC 
# MAGIC **Why:** Each payload record needs its source file context for traceability and regulatory reporting. This enrichment allows queries that filter by submission date, file batch, or sender information.

# COMMAND ----------

hdr_pyld_df = raw_pyld_df.join(hdr_pyld_mtdt_rgx_df, on="file_path")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Define Output Table and Checkpoint Paths
# MAGIC 
# MAGIC **What:** Set the destination table name and checkpoint location for the streaming write

# COMMAND ----------

raw_table = f"{table_prefix}_raw"
raw_table_checkpoint = f"{checkpoint_path}/{raw_table}_raw_table_checkpoint"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Write to Delta Raw Table
# MAGIC 
# MAGIC **What:** Stream the enriched XML data into a Delta Lake table with checkpointing
# MAGIC 
# MAGIC **Why:** Delta Lake provides ACID transactions, time travel, and schema evolution. Checkpointing ensures exactly-once processing - if the job fails, it resumes from the last successful batch. The `availableNow` trigger processes all available data then stops, ideal for scheduled jobs.
# MAGIC 
# MAGIC **How:** Create catalog and schema if needed, then write the streaming DataFrame to Delta format with append mode.

# COMMAND ----------

spark.sql(f"CREATE CATALOG IF NOT EXISTS {catalog}")
spark.sql(f"CREATE SCHEMA IF NOT EXISTS {catalog}.{raw_schema}")

# COMMAND ----------

try:
  (hdr_pyld_df.writeStream
    .trigger(availableNow=True)
    .format("delta")
    .outputMode("append")
    .option("checkpointLocation", raw_table_checkpoint) 
    .toTable(f"{catalog}.{raw_schema}.{raw_table}")
  )

except PySparkException as ex:
  print("Error Class       : " + ex.getErrorClass())
  print("Message parameters: " + str(ex.getMessageParameters()))
  print("SQLSTATE          : " + ex.getSqlState())
  print(ex)
